#!/usr/bin/env zsh

git clone -b v0.11.1 https://github.com/neovim/neovim.git $HOME/personal/neovim
brew install cmake gettext lua

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

