#!/usr/bin/env zsh
git clone https://github.com/koekeishiya/skhd $HOME/personal/skhd
cd $HOME/personal/skhd
brew install cmake xcode
make install
sudo cp ./bin/skhd /usr/local/bin/skhd
skhd --start-service
